// src/analytics/schema.js
export const ANALYTICS_SCHEMA = {
  add_item_button_click: { params: { screen: 'string', platform: 'string' } },
  add_item_save_click:   { params: { is_edit: 'bool', has_photo: 'bool', remind_days: 'int', edible_days: 'int' } },
  add_item_icon_click:   { params: {} },
  add_item_icon_source:  { params: { source: 'camera|library|cancel' } },
  add_item_icon_set:     { params: { has_photo: 'bool' } },
  add_item_scan_click:   { params: {} },
  add_item_scan_source:  { params: { source: 'camera|library|cancel' } },
  add_item_scan_cancel:  { params: {} },
  add_item_scan_complete:{ params: { success: 'bool' } },
  add_item_product_open: { params: {} },
  add_item_product_set:  { params: { date: 'YYYY-MM-DD' } },
  add_item_expiry_open:  { params: {} },
  add_item_expiry_set:   { params: { date: 'YYYY-MM-DD' } },
  add_item_duration_open:{ params: {} },
  add_item_duration_set: { params: { sign: 'int', y: 'int', m: 'int', d: 'int', total_days: 'int' } },
  add_item_remind_open:  { params: {} },
  add_item_remind_set:   { params: { days: 'int' } },
  add_item_notes_open:   { params: {} },
  add_item_category_pick:{ params: { category_key: 'string' } },

  home_open:             { params: {} },
  home_close:            { params: { duration_ms: 'int' } },
  home_filter_open_click:{ params: {} },
  home_search_toggle:    { params: { open: 'bool' } },
  home_search_clear:     { params: {} },
  home_clear_click:      { params: { count: 'int' } },
  home_clear_cancel:     { params: { count: 'int' } },
  home_clear_confirm:    { params: { count: 'int' } },

  filter_expire_days_change: { params: { days: 'int|null' } },
  filter_expire_days_clear:  { params: {} },
  filter_category_select:    { params: { category: 'string', category_key: 'string', category_label: 'string' } },
  filter_reset_click:        { params: {} },

  item_card_click:        { params: { item_id: 'string|null', has_photo: 'bool', days_remaining: 'int|null' } },
  item_card_delete_click: { params: { item_id: 'string|null', has_photo: 'bool', days_remaining: 'int|null' } },

  settings_open:          { params: { platform: 'string', scans_left: 'int' } },
  settings_close:         { params: { duration_ms: 'int' } },
  settings_more_scans_click:{ params: { ad_ready: 'bool', scans_left: 'int' } },
  rewarded_loaded:        { params: { unit: 'string', npa: 'bool' } },
  rewarded_show_attempt:  { params: {} },
  rewarded_show_failed:   { params: {} },
  rewarded_closed:        { params: {} },
  rewarded_reward:        { params: { amount: 'int', scans_left_after: 'int' } },
  rewarded_error:         { params: { message: 'string' } },
  scan_bonus_daily:       { params: { amount: 'int', scans_left_after: 'int' } },
  scan_bonus_daily_cooldown:{ params: { hours_left: 'int' } },

  export_zip_start:       { params: { item_count: 'int' } },
  export_zip_done:        { params: { item_count: 'int' } },
  export_zip_shared:      { params: { item_count: 'int' } },
  export_zip_error:       { params: { message: 'string' } },

  import_zip_click:       { params: {} },
  import_zip_ready:       { params: { item_count: 'int' } },
  import_zip_confirm_add: { params: { item_count: 'int' } },
  import_zip_error:       { params: { message: 'string' } },

  settings_user_guide_click: { params: {} },
  settings_contact_click:    { params: {} },
  settings_privacy_click:    { params: { url: 'string' } },

  scan_success:           { params: { method: 'string', has_photo: 'bool' } },
  reward_granted:         { params: { amount: 'int' } },
};
